var BRICK_LIST = [
    "tile_6x1",
    "plate_6x2",
    "plate_14x2",
    "plate_4x4",
    "plate-corner-cut_3x3",
    "plate-corner-cut_6x6",
    "tile-round-quarter_1x1",
    "tile-triangle_2x2",
    "plate-corner-cut_2x2",
    "brick_1x1",
    "plate_3x1",
    "plate_1x1",
    "brick_3x1",
    "plate_3x2",
    "window-frame_2x2",
    "window-frame_3x2",
    "window-frame_4x3",
    "tile_4x1",
    "brick_4x1",
    "plate_4x2",
    "plate_4x1",
    "tile-corner-curved_3x1",
    "brick-corner-curved_3x1",
    "window-frame-corner-curved_3x2",
    "window-frame-corner-curved_3x3",
    "window-frame-corner-curved_3x4",
    "tile-corner-curved_4x2",
    "brick-corner-curved_4x2",
    "tile-corner-curved_4x1",
    "brick-corner-curved_4x1",
    "brick-corner-round_1x1",
    "brick-round_1x1",
    "brick-round_2x1",
    "brick-round_3x1",
    "brick-round_4x1",
    "brick-round_6x1",
    "brick-round_8x1",
]

var BRICK_COLORS = [
    { name: "White", hex: "#FFFFFF" },
    { name: "Black", hex: "#05131D" },
    { name: "Reddish Brown", hex: "#582A12" },
    { name: "Sand Green", hex: "#A0BCAC" },
    { name: "Rust", hex: "#B31004" },
    { name: "Tan", hex: "#E4CD9E" },
    { name: "Dark Bluish Gray", hex: "#6C6E68" }
]